upstream trafficlight {
    server red-app:80;
    server yellow-app:80;
    server green-app:80;
}

server {
    listen 80;

    auth_basic "Restricted Access";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        proxy_pass http://trafficlight;
    }
}